default:
  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
  autoload:
    '': %paths.base%/../features/bootstrap
  suites:
    default:
      paths:
        - %paths.base%/../features
      contexts:
        [\Colourspace\FeatureContext]
